/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Titan API
 * OpenAPI spec version: v1
 */
export type GetApiUserFavouriteParams = {
PageSize?: number;
PageNumber?: number;
};

export type GetApiAdminUserParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
RoleName?: string;
};

export type GetApiAdminTagParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminRequestLogMediaRequestLogParams = {
RequestLogId?: string;
PageSize?: number;
PageNumber?: number;
};

export type GetApiAdminRequestLogMediaParams = {
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminRequestLogParams = {
RequestId?: string;
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
StartDateTime?: string;
EndDateTime?: string;
};

export type GetApiAdminRequestSellRentParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
IsRent?: boolean;
};

export type GetApiAdminRequestBuyRentParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
IsRent?: boolean;
};

export type GetApiAdminRequestEnquiryParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminRequestDealerParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminRequestInsuranceParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminRequestCollaboratorParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminRequestParams = {
RequestType?: RequestType;
RequestStatus?: RequestStatus;
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiRequestParams = {
PageSize?: number;
PageNumber?: number;
RequestType?: RequestType;
RequestStatus?: RequestStatus;
};

export type GetApiPurchaseParams = {
PageSize?: number;
PageNumber?: number;
};

export type GetApiNotificationParams = {
PageSize?: number;
PageNumber?: number;
};

export type GetApiMachineTypeParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminMachineMediaMachineParams = {
MachineId?: string;
PageSize?: number;
PageNumber?: number;
};

export type GetApiAdminMachineMediaParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiMachineMakeParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiMachineParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiListingTagTagsParams = {
Id?: string;
ListingId?: string;
PageSize?: number;
PageNumber?: number;
};

export type GetApiListingTagListingsParams = {
Id?: string;
TagId?: string;
PageSize?: number;
PageNumber?: number;
};

export type GetApiAdminListingMediaListingParams = {
ListingId?: string;
PageSize?: number;
PageNumber?: number;
};

export type GetApiAdminListingMediaParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminListingParams = {
SearchPhrase?: string;
MachineTypeIds?: string[];
MachineMakeIds?: string[];
LowestPrice?: number;
HighestPrice?: number;
Location?: StatesAndTerritoriesOfMalaysia;
Year?: number;
ListingType?: ListingType;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
DistributorProfileId?: string;
SellerId?: string;
ListingCondition?: ListingCondition;
ListingStatus?: ListingStatus;
};

export type GetApiListingParams = {
SearchPhrase?: string;
MachineTypeIds?: string[];
MachineMakeIds?: string[];
LowestPrice?: number;
HighestPrice?: number;
Location?: StatesAndTerritoriesOfMalaysia;
Year?: number;
ListingType?: ListingType;
ListingCondition?: ListingCondition;
ListingStatus?: ListingStatus;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
DistributorProfileId?: string;
};

export type GetApiAdminIndustryParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminDistributorParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
IsInternationalDistributor?: boolean;
};

export type GetApiDistributorParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
IsInternationalDistributor?: boolean;
};

export type GetApiAdminCollaboratorParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminBusinessAffiliateParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
OperationalRegion?: StatesAndTerritoriesOfMalaysia;
};

export type GetApiBrowsingHistoryParams = {
SessionId?: string;
PageSize?: number;
PageNumber?: number;
};

export type GetApiAdminAppointmentRequestParams = {
RequestId?: string;
PageSize?: number;
PageNumber?: number;
AppointmentStatus?: AppointmentStatus;
AppointmentType?: AppointmentType;
};

export type GetApiAdminAppointmentBusinessAffiliateParams = {
BusinessAffiliateProfileId?: string;
PageSize?: number;
PageNumber?: number;
AppointmentStatus?: AppointmentStatus;
AppointmentType?: AppointmentType;
};

export type GetApiAdminAppointmentParams = {
StartDateTime?: string;
EndDateTime?: string;
AppointmentStatus?: AppointmentStatus;
AppointmentType?: AppointmentType;
PageSize?: number;
PageNumber?: number;
RequestId?: string;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiBusinessAffiliateAppointmentParams = {
BusinessAffiliateProfileId?: string;
PageSize?: number;
PageNumber?: number;
AppointmentStatus?: AppointmentStatus;
AppointmentType?: AppointmentType;
};

export type GetApiAppointmentRequestParams = {
RequestId?: string;
PageSize?: number;
PageNumber?: number;
AppointmentStatus?: AppointmentStatus;
AppointmentType?: AppointmentType;
};

export type GetApiAppointmentParams = {
PageSize?: number;
PageNumber?: number;
AppointmentStatus?: AppointmentStatus;
AppointmentType?: AppointmentType;
};

export type GetApiAdminAdvertisementMediaParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdvertisementCategoryParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdvertisementParams = {
SearchPhrase?: string;
AdvertisementCategoryIds?: string[];
IsSystemAdvertisement?: boolean;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export type GetApiAdminAdministratorParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
AdministratorType?: AdministratorType;
};

export type GetApiAdminAddressParams = {
SearchPhrase?: string;
PageSize?: number;
PageNumber?: number;
SortBy?: string;
SortDirection?: ListSortDirection;
};

export interface VerifyOtpDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  otp?: string | null;
}

export interface UserProfileDto {
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  picFullName?: string | null;
  /** @nullable */
  profilePictureUrl?: string | null;
  userId?: string;
}

export interface UserProfileDtoDataResponseDto {
  data?: UserProfileDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface UserFavouriteDto {
  id?: string;
  listing?: ListingDto;
  listingId?: string;
  userId?: string;
}

export interface UserFavouriteDtoPagedResult {
  /** @nullable */
  items?: UserFavouriteDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface UserFavouriteDtoDataResponseDto {
  data?: UserFavouriteDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface UserDto {
  /** @nullable */
  companyName?: string | null;
  createdAt?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  id?: string;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  picFullName?: string | null;
  /** @nullable */
  profilePictureUrl?: string | null;
  roleName?: RoleName;
  /** @nullable */
  roles?: string[] | null;
  updatedAt?: string;
  /** @nullable */
  username?: string | null;
}

export interface UserDtoPagedResult {
  /** @nullable */
  items?: UserDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface UpsertTagCommand {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  title?: string | null;
}

export interface UpsertRequestLogMediaCommand {
  /** @nullable */
  id?: string | null;
  isThumbnail?: boolean;
  /** @nullable */
  mediaFile?: Blob | null;
  /** @nullable */
  mediaUrl?: string | null;
  /** @nullable */
  requestLogId?: string | null;
  /** @nullable */
  title?: string | null;
  type?: MediaType;
}

export interface UpsertMachineTypeCommand {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  typeIconFile?: Blob | null;
  /** @nullable */
  typeIconUrl?: string | null;
}

export interface UpsertMachineMediaCommand {
  /** @nullable */
  id?: string | null;
  isThumbnail?: boolean;
  /** @nullable */
  machineId?: string | null;
  /** @nullable */
  mediaFile?: Blob | null;
  /** @nullable */
  mediaUrl?: string | null;
  /** @nullable */
  title?: string | null;
  type?: MediaType;
}

export interface UpsertMachineMakeCommand {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  logoImageFile?: Blob | null;
  /** @nullable */
  logoImageUrl?: string | null;
  /** @nullable */
  name?: string | null;
}

export interface UpsertMachineCommand {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  machineMakeId?: string | null;
  /** @nullable */
  machineMediaIds?: string[] | null;
  /** @nullable */
  machineTypeId?: string | null;
  /** @nullable */
  mediaFiles?: Blob[] | null;
  /** @nullable */
  modelNo?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  thumbnailImage?: Blob | null;
  /** @nullable */
  thumbnailUrl?: string | null;
}

export interface UpsertListingMediaCommand {
  /** @nullable */
  id?: string | null;
  isCatalog?: boolean;
  isThumbnail?: boolean;
  /** @nullable */
  listingId?: string | null;
  /** @nullable */
  mediaFile?: Blob | null;
  /** @nullable */
  mediaUrl?: string | null;
  /** @nullable */
  title?: string | null;
  type?: MediaType;
}

export interface UpsertListingCommand {
  /** @nullable */
  catalogUrl?: string | null;
  /** @nullable */
  chasisNo?: string | null;
  condition?: ListingCondition;
  /** @nullable */
  dealerProfileId?: string | null;
  /** @nullable */
  distributorProfileId?: string | null;
  /** @nullable */
  engineNo?: string | null;
  /** @nullable */
  hourMeter?: number | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  listingMediaIds?: string[] | null;
  listingStatus?: ListingStatus;
  listingType?: ListingType;
  location?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  machineId?: string | null;
  /** @nullable */
  mediaFiles?: Blob[] | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  regCard?: boolean | null;
  /** @nullable */
  sellerId?: string | null;
  /** @nullable */
  thumbnailImage?: Blob | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  year?: number | null;
}

export interface UpsertIndustryCommand {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
}

export interface UpsertFAQCommand {
  /** @nullable */
  answer?: string | null;
  category?: FAQCategory;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  question?: string | null;
}

export interface UpsertDistributorCommand {
  /** @nullable */
  addressId?: string | null;
  /** @nullable */
  companyBackgroundImageUrl?: string | null;
  /** @nullable */
  companyCatalogUrl?: string | null;
  /** @nullable */
  companyDescription?: string | null;
  /** @nullable */
  companyEmail?: string | null;
  /** @nullable */
  companyLogoImageUrl?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  companyPhoneNumber?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  isInternationalDistributor?: boolean | null;
  /** @nullable */
  personInChargeFullName?: string | null;
  /** @nullable */
  picEmail?: string | null;
  /** @nullable */
  picPhoneNumber?: string | null;
  /** @nullable */
  username?: string | null;
}

export interface UpsertCollaboratorCommand {
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  industryId?: string | null;
  /** @nullable */
  leadAttendeeId?: string | null;
  /** @nullable */
  personInChargeFullName?: string | null;
  /** @nullable */
  picEmail?: string | null;
  /** @nullable */
  picPhoneNumber?: string | null;
}

export interface UpsertBusinessAffiliateCommand {
  /** @nullable */
  addressId?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  lastName?: string | null;
  operationalRegion?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  profileImageUrl?: string | null;
  /** @nullable */
  username?: string | null;
}

export interface UpsertAppointmentCommand {
  /** @nullable */
  addressId?: string | null;
  /** @nullable */
  appointmentDateTime?: string | null;
  appointmentStatus?: AppointmentStatus;
  appointmentType?: AppointmentType;
  /** @nullable */
  businessAffiliateId?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  requestId?: string | null;
}

export interface UpsertAdvertisementMediaCommand {
  /** @nullable */
  advertisementId?: string | null;
  /** @nullable */
  id?: string | null;
  isThumbnail?: boolean;
  /** @nullable */
  mediaFile?: Blob | null;
  /** @nullable */
  mediaUrl?: string | null;
  /** @nullable */
  title?: string | null;
  type?: MediaType;
}

export interface UpsertAdvertisementCommand {
  /** @nullable */
  advertisementCategoryId?: string | null;
  /** @nullable */
  advertisementMediaIds?: string[] | null;
  advertisementStatus?: AdvertisementStatus;
  /** @nullable */
  collaboratorId?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  isSystemAdvertisement?: boolean | null;
  /** @nullable */
  mediaFiles?: Blob[] | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  thumbnailImage?: Blob | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  urlToRedirectTo?: string | null;
}

export interface UpsertAdvertisementCategoryCommand {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
}

export interface UpsertAdministratorCommand {
  /** @nullable */
  addressId?: string | null;
  administratorType?: AdministratorType;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  profileImageUrl?: string | null;
  /** @nullable */
  reportToId?: string | null;
  /** @nullable */
  subordinateIds?: string[] | null;
  /** @nullable */
  username?: string | null;
}

export interface UpsertAddressCommand {
  /** @nullable */
  city?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  state?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  street?: string | null;
  /** @nullable */
  street2?: string | null;
  /** @nullable */
  zipCode?: string | null;
}

export interface UpdateUserProfileCommand {
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  picFullName?: string | null;
  /** @nullable */
  profilePicture?: Blob | null;
  /** @nullable */
  profilePictureUrl?: string | null;
  userId?: string;
}

export interface UpdateDistributorCommand {
  /** @nullable */
  addressId?: string | null;
  /** @nullable */
  companyBackgroundImageUrl?: string | null;
  /** @nullable */
  companyCatalogUrl?: string | null;
  /** @nullable */
  companyDescription?: string | null;
  /** @nullable */
  companyEmail?: string | null;
  /** @nullable */
  companyLogoImageUrl?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  isInternationalDistributor?: boolean | null;
  /** @nullable */
  personInChargeFullName?: string | null;
  /** @nullable */
  picEmail?: string | null;
  /** @nullable */
  picPhoneNumber?: string | null;
}

export interface UpdateBusinessAffiliateCommand {
  /** @nullable */
  addressId?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  operationalRegion?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  profileImageUrl?: string | null;
}

export interface UnassignUserRoleCommand {
  /** @nullable */
  roleName?: string | null;
  userId?: string;
}

export interface TopicNotificationRequestDto {
  /** @nullable */
  body?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  topic?: string | null;
}

export interface TokenDto {
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  token?: string | null;
}

export interface TagDto {
  /** @nullable */
  description?: string | null;
  id?: string;
  /** @nullable */
  title?: string | null;
}

export interface TagDtoPagedResult {
  /** @nullable */
  items?: TagDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export type StatesAndTerritoriesOfMalaysia = typeof StatesAndTerritoriesOfMalaysia[keyof typeof StatesAndTerritoriesOfMalaysia];



export const StatesAndTerritoriesOfMalaysia = {
  Default: 'Default',
  Johor: 'Johor',
  Kedah: 'Kedah',
  Kelantan: 'Kelantan',
  Malacca: 'Malacca',
  NegeriSembilan: 'NegeriSembilan',
  Pahang: 'Pahang',
  Penang: 'Penang',
  Perak: 'Perak',
  Perlis: 'Perlis',
  Sabah: 'Sabah',
  Sarawak: 'Sarawak',
  Selangor: 'Selangor',
  Terengganu: 'Terengganu',
  KualaLumpur: 'KualaLumpur',
  Labuan: 'Labuan',
  Putrajaya: 'Putrajaya',
} as const;

export interface SellRentRequestDetailDto {
  /** @nullable */
  hourMeter?: string | null;
  id?: string;
  isRent?: boolean;
  location?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  machineMake?: string | null;
  /** @nullable */
  machineType?: string | null;
  /** @nullable */
  modelNo?: string | null;
  regCard?: boolean;
  requestId?: string;
}

export interface SasUploadMediaDto {
  /** @nullable */
  fileUrlPrefix?: string | null;
  /** @nullable */
  sasUrlForUploadMedia?: string | null;
}

export type RoleName = typeof RoleName[keyof typeof RoleName];



export const RoleName = {
  Default: 'Default',
  User: 'User',
  Dealer: 'Dealer',
  Distributor: 'Distributor',
  Admin: 'Admin',
  BusinessAffiliate: 'BusinessAffiliate',
  Collaborator: 'Collaborator',
} as const;

export interface ResponseDto {
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface ResetPasswordRequestDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  token?: string | null;
}

export type RequestType = typeof RequestType[keyof typeof RequestType];



export const RequestType = {
  Default: 'Default',
  Buy: 'Buy',
  Sell: 'Sell',
  Rent: 'Rent',
  RentOut: 'RentOut',
  Insurance: 'Insurance',
  Dealer: 'Dealer',
  Collaborator: 'Collaborator',
  Advertisement: 'Advertisement',
  Enquiry: 'Enquiry',
} as const;

export type RequestStatus = typeof RequestStatus[keyof typeof RequestStatus];



export const RequestStatus = {
  Default: 'Default',
  Pending: 'Pending',
  Appointment: 'Appointment',
  PendingPayment: 'PendingPayment',
  PendingDelivery: 'PendingDelivery',
  Completed: 'Completed',
  Incomplete: 'Incomplete',
} as const;

export interface RequestSummaryDto {
  buyRentRequestDetail?: BuyRentRequestDetailDto;
  createdAt?: string;
  id?: string;
  /** @nullable */
  requestorName?: string | null;
  requestStatus?: RequestStatus;
  requestType?: RequestType;
  sellRentRequestDetail?: SellRentRequestDetailDto;
}

export interface RequestLogSummaryDto {
  fromStatus?: RequestStatus;
  id?: string;
  /** @nullable */
  remark?: string | null;
  requestId?: string;
  toStatus?: RequestStatus;
}

export interface RequestLogMediaDto {
  id?: string;
  isThumbnail?: boolean;
  /** @nullable */
  mediaUrl?: string | null;
  requestLogId?: string;
  /** @nullable */
  title?: string | null;
  type?: MediaType;
}

export interface RequestLogMediaDtoPagedResult {
  /** @nullable */
  items?: RequestLogMediaDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface RequestLogMediaDtoDataResponseDto {
  data?: RequestLogMediaDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface RequestLogDto {
  appointment?: AppointmentDto;
  createdAt?: string;
  createdBy?: string;
  createdByUser?: UserDto;
  fromStatus?: RequestStatus;
  id?: string;
  purchase?: PurchaseDto;
  /** @nullable */
  remark?: string | null;
  requestId?: string;
  /** @nullable */
  requestLogMedias?: RequestLogMediaDto[] | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  toStatus?: RequestStatus;
}

export interface RequestLogDtoPagedResult {
  /** @nullable */
  items?: RequestLogDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface RequestDto {
  /** @nullable */
  appointments?: AppointmentDto[] | null;
  buyRentRequestDetail?: BuyRentRequestDetailDto;
  collaboratorRequestDetail?: CollaboratorRequestDetailDto;
  createdAt?: string;
  dealerRequestDetail?: DealerRequestDetailDto;
  enquiryDetail?: EnquiryDetailDto;
  id?: string;
  insuranceRequestDetail?: InsuranceRequestDetailDto;
  /** @nullable */
  requestLogs?: RequestLogDto[] | null;
  /** @nullable */
  requestorEmail?: string | null;
  /** @nullable */
  requestorName?: string | null;
  /** @nullable */
  requestorPhoneNumber?: string | null;
  requestStatus?: RequestStatus;
  requestType?: RequestType;
  sellRentRequestDetail?: SellRentRequestDetailDto;
  updatedAt?: string;
  user?: UserDto;
}

export interface RequestDtoPagedResult {
  /** @nullable */
  items?: RequestDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface RequestDtoDataResponseDto {
  data?: RequestDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface RegisterDto {
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  otpCode?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  picFullName?: string | null;
}

export interface PurchaseDto {
  createdAt?: string;
  id?: string;
  listing?: ListingDto;
  listingId?: string;
  request?: RequestSummaryDto;
  requestId?: string;
  requestLog?: RequestLogSummaryDto;
  requestLogId?: string;
  user?: UserDto;
}

export interface PurchaseDtoPagedResult {
  /** @nullable */
  items?: PurchaseDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface PhoneNumberExistsResponseDto {
  phoneNumberExists?: boolean;
}

export interface PhoneNumberExistsRequestDto {
  /** @nullable */
  phoneNumber?: string | null;
}

export interface NotificationRequestDto {
  /** @nullable */
  body?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  token?: string | null;
}

export interface NotificationDto {
  /** @nullable */
  body?: string | null;
  createdAt?: string;
  /** @nullable */
  dataPayload?: string | null;
  id?: string;
  isProcessed?: boolean;
  /** @nullable */
  processedAt?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  token?: string | null;
  /** @nullable */
  topic?: string | null;
}

export interface NotificationDtoPagedResult {
  /** @nullable */
  items?: NotificationDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export type MediaType = typeof MediaType[keyof typeof MediaType];



export const MediaType = {
  Default: 'Default',
  Document: 'Document',
  Image: 'Image',
  Video: 'Video',
} as const;

export interface MachineTypeDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  typeIconUrl?: string | null;
}

export interface MachineMediaDto {
  id?: string;
  isThumbnail?: boolean;
  machineId?: string;
  /** @nullable */
  mediaUrl?: string | null;
  /** @nullable */
  title?: string | null;
  type?: MediaType;
}

export interface MachineMediaDtoPagedResult {
  /** @nullable */
  items?: MachineMediaDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface MachineMediaDtoDataResponseDto {
  data?: MachineMediaDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface MachineMakeDto {
  id?: string;
  /** @nullable */
  logoImageUrl?: string | null;
  /** @nullable */
  name?: string | null;
}

export interface MachineDetailDto {
  id?: string;
  machineId?: string;
  /** @nullable */
  modelNo?: string | null;
}

export interface MachineDto {
  highestPrice?: number;
  id?: string;
  lowestPrice?: number;
  machineDetail?: MachineDetailDto;
  machineMake?: MachineMakeDto;
  /** @nullable */
  machineMedias?: MachineMediaDto[] | null;
  machineType?: MachineTypeDto;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
}

export interface MachineDtoPagedResult {
  /** @nullable */
  items?: MachineDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface MachineDtoDataResponseDto {
  data?: MachineDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface LoginDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

export type ListingType = typeof ListingType[keyof typeof ListingType];



export const ListingType = {
  Default: 'Default',
  Sell: 'Sell',
  Rent: 'Rent',
} as const;

export interface ListingTagDto {
  id?: string;
  listingId?: string;
  tagId?: string;
}

export type ListingStatus = typeof ListingStatus[keyof typeof ListingStatus];



export const ListingStatus = {
  Default: 'Default',
  Draft: 'Draft',
  Published: 'Published',
  Sold: 'Sold',
  Unavailable: 'Unavailable',
} as const;

export interface ListingMediaDto {
  id?: string;
  isCatalog?: boolean;
  isThumbnail?: boolean;
  listingId?: string;
  /** @nullable */
  mediaUrl?: string | null;
  /** @nullable */
  title?: string | null;
  type?: MediaType;
}

export interface ListingMediaDtoPagedResult {
  /** @nullable */
  items?: ListingMediaDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface ListingMediaDtoDataResponseDto {
  data?: ListingMediaDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface ListingDtoDataResponseDto {
  data?: ListingDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface ListingDetailDto {
  /** @nullable */
  chasisNo?: string | null;
  /** @nullable */
  engineNo?: string | null;
  hourMeter?: number;
  id?: string;
  listingId?: string;
  regCard?: boolean;
  year?: number;
}

export type ListingCondition = typeof ListingCondition[keyof typeof ListingCondition];



export const ListingCondition = {
  Default: 'Default',
  New: 'New',
  Used: 'Used',
  Recon: 'Recon',
} as const;

export interface ListingDto {
  /** @nullable */
  catalogUrl?: string | null;
  condition?: ListingCondition;
  id?: string;
  isUserFavourite?: boolean;
  listingDetail?: ListingDetailDto;
  /** @nullable */
  listingMedias?: ListingMediaDto[] | null;
  listingStatus?: ListingStatus;
  listingType?: ListingType;
  location?: StatesAndTerritoriesOfMalaysia;
  machine?: MachineDto;
  /** @nullable */
  name?: string | null;
  price?: number;
  /** @nullable */
  thumbnailUrl?: string | null;
}

export interface ListingDtoPagedResult {
  /** @nullable */
  items?: ListingDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export type ListSortDirection = typeof ListSortDirection[keyof typeof ListSortDirection];



export const ListSortDirection = {
  Ascending: 'Ascending',
  Descending: 'Descending',
} as const;

export type InterestType = typeof InterestType[keyof typeof InterestType];



export const InterestType = {
  Default: 'Default',
  BookMachine: 'BookMachine',
  ViewFullInspectionReport: 'ViewFullInspectionReport',
  Others: 'Others',
} as const;

export type InsuranceType = typeof InsuranceType[keyof typeof InsuranceType];



export const InsuranceType = {
  Default: 'Default',
  HeavyEquipmentAllRiskInsurance: 'HeavyEquipmentAllRiskInsurance',
  EquipmentAllRiskInsurance: 'EquipmentAllRiskInsurance',
  ContractorAllRiskInsurance: 'ContractorAllRiskInsurance',
  WorkmanCompensation: 'WorkmanCompensation',
  PerformanceBond: 'PerformanceBond',
  Others: 'Others',
} as const;

export interface InsuranceRequestDetailDto {
  id?: string;
  insuranceType?: InsuranceType;
  location?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  machineMake?: string | null;
  /** @nullable */
  machineType?: string | null;
  /** @nullable */
  modelName?: string | null;
  registrationCard?: boolean;
  /** @nullable */
  registrationNo?: string | null;
  requestId?: string;
  /** @nullable */
  sumInsured?: string | null;
}

export interface IndustryDto {
  id?: string;
  /** @nullable */
  name?: string | null;
}

export interface GetSasUrlForUploadRequestLogMediaQuery {
  /** @nullable */
  fileName?: string | null;
}

export interface GetSasUrlForUploadProfilePictureQuery {
  /** @nullable */
  fileName?: string | null;
}

export interface GetSasUrlForUploadMachineTypeIconQuery {
  /** @nullable */
  fileName?: string | null;
}

export interface GetSasUrlForUploadMachineMakeLogoQuery {
  /** @nullable */
  fileName?: string | null;
}

export interface GetSasUrlForUploadListingMediaQuery {
  /** @nullable */
  fileName?: string | null;
}

export interface GetSasUrlForUploadDistributorMediaQuery {
  /** @nullable */
  fileName?: string | null;
}

export interface GetSasUrlForUploadBusinessAffiliateMediaQuery {
  /** @nullable */
  fileName?: string | null;
}

export interface GetSasUrlForUploadAdvertisementMediaQuery {
  /** @nullable */
  fileName?: string | null;
}

export interface GetSasUrlForUploadAdministratorMediaQuery {
  /** @nullable */
  fileName?: string | null;
}

export interface GenerateOtpForRegistrationDto {
  /** @nullable */
  email?: string | null;
}

export interface ForgotPasswordRequestDto {
  /** @nullable */
  email?: string | null;
}

export interface FilterDto {
  /** @nullable */
  machineMakes?: MachineMakeDto[] | null;
  /** @nullable */
  machineTypes?: MachineTypeDto[] | null;
  totalMachineMakes?: number;
  totalMachineTypes?: number;
}

export interface FilterDtoDataResponseDto {
  data?: FilterDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export type FAQCategory = typeof FAQCategory[keyof typeof FAQCategory];



export const FAQCategory = {
  Default: 'Default',
  General: 'General',
  Buy: 'Buy',
  Sell: 'Sell',
  Rent: 'Rent',
  RentOut: 'RentOut',
  Insurance: 'Insurance',
  Dealer: 'Dealer',
  Advertisement: 'Advertisement',
} as const;

export interface FAQDto {
  /** @nullable */
  answer?: string | null;
  category?: FAQCategory;
  id?: string;
  /** @nullable */
  question?: string | null;
}

export interface EnquiryDetailDto {
  /** @nullable */
  enquiryRemarks?: string | null;
  id?: string;
  requestId?: string;
}

export interface EmailExistsResponseDto {
  /** @nullable */
  companyName?: string | null;
  emailExists?: boolean;
  /** @nullable */
  errorMessage?: string | null;
  otpGenerated?: boolean;
  /** @nullable */
  picFullName?: string | null;
}

export interface EmailExistsRequestDto {
  /** @minLength 1 */
  email: string;
}

export interface EmailDataDto {
  /** @nullable */
  emailBody?: string | null;
  /** @nullable */
  emailSubject?: string | null;
  /** @nullable */
  emailToName?: string | null;
  /** @nullable */
  toEmail?: string | null;
}

export interface DistributorSummaryDto {
  /** @nullable */
  companyBackgroundImageUrl?: string | null;
  /** @nullable */
  companyCatalogUrl?: string | null;
  /** @nullable */
  companyDescription?: string | null;
  /** @nullable */
  companyEmail?: string | null;
  /** @nullable */
  companyLogoImageUrl?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  companyPhoneNumber?: string | null;
  id?: string;
  isInternationalDistributor?: boolean;
  /** @nullable */
  username?: string | null;
}

export interface DistributorSummaryDtoPagedResult {
  /** @nullable */
  items?: DistributorSummaryDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface DistributorDetailDto {
  companyAddress?: AddressDto;
  /** @nullable */
  companyBackgroundImageUrl?: string | null;
  /** @nullable */
  companyCatalogUrl?: string | null;
  /** @nullable */
  companyDescription?: string | null;
  /** @nullable */
  companyEmail?: string | null;
  /** @nullable */
  companyLogoImageUrl?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  companyPhoneNumber?: string | null;
  id?: string;
  isInternationalDistributor?: boolean;
  /** @nullable */
  personInChargeFullName?: string | null;
  /** @nullable */
  picEmail?: string | null;
  /** @nullable */
  picPhoneNumber?: string | null;
  user?: UserDto;
  userId?: string;
  /** @nullable */
  username?: string | null;
}

export interface DistributorDetailDtoPagedResult {
  /** @nullable */
  items?: DistributorDetailDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface DeleteAccountCommand {
  /** @nullable */
  otpCode?: string | null;
  userId?: string;
}

export interface DealerRequestDetailDto {
  /** @nullable */
  dealershipName?: string | null;
  id?: string;
  location?: StatesAndTerritoriesOfMalaysia;
  requestId?: string;
}

export interface CreateSellRentRequestCommand {
  /** @nullable */
  hourMeter?: number | null;
  isRent?: boolean;
  location?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  machineMake?: string | null;
  /** @nullable */
  machineType?: string | null;
  /** @nullable */
  modelNo?: string | null;
  regCard?: boolean;
  /** @nullable */
  requestorEmail?: string | null;
  /** @nullable */
  requestorName?: string | null;
  /** @nullable */
  requestorPhoneNumber?: string | null;
}

export interface CreateRequestLogCommand {
  /** @nullable */
  addressId?: string | null;
  /** @nullable */
  appointmentDateTime?: string | null;
  appointmentType?: AppointmentType;
  /** @nullable */
  businessAffiliateProfileId?: string | null;
  /** @nullable */
  mediaFiles?: Blob[] | null;
  /** @nullable */
  remark?: string | null;
  requestId?: string;
  /** @nullable */
  requestLogMediaIds?: string[] | null;
  /** @nullable */
  thumbnailImage?: Blob | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  toStatus?: RequestStatus;
}

export interface CreateListingTagCommand {
  /** @nullable */
  listingId?: string | null;
  /** @nullable */
  tagId?: string | null;
}

export interface CreateInsuranceRequestCommand {
  insuranceType?: InsuranceType;
  location?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  machineMake?: string | null;
  /** @nullable */
  machineType?: string | null;
  /** @nullable */
  modelName?: string | null;
  registrationCard?: boolean;
  /** @nullable */
  registrationNo?: string | null;
  /** @nullable */
  requestorEmail?: string | null;
  /** @nullable */
  requestorName?: string | null;
  /** @nullable */
  requestorPhoneNumber?: string | null;
  /** @nullable */
  sumInsured?: string | null;
}

export interface CreateEnquiryCommand {
  /** @nullable */
  enquiryRemarks?: string | null;
  /** @nullable */
  requestorEmail?: string | null;
  /** @nullable */
  requestorName?: string | null;
  /** @nullable */
  requestorPhoneNumber?: string | null;
}

export interface CreateDealerRequestCommand {
  /** @nullable */
  dealershipName?: string | null;
  location?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  requestorEmail?: string | null;
  /** @nullable */
  requestorName?: string | null;
  /** @nullable */
  requestorPhoneNumber?: string | null;
  /** @nullable */
  zipCode?: string | null;
}

export interface CreateCollaboratorRequestCommand {
  /** @nullable */
  companyName?: string | null;
  location?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  remarks?: string | null;
  /** @nullable */
  requestorEmail?: string | null;
  /** @nullable */
  requestorName?: string | null;
  /** @nullable */
  requestorPhoneNumber?: string | null;
}

export interface CreateBuyRentRequestCommand {
  interestType?: InterestType;
  isRent?: boolean;
  listingId?: string;
  /** @nullable */
  requestorEmail?: string | null;
  /** @nullable */
  requestorName?: string | null;
  /** @nullable */
  requestorPhoneNumber?: string | null;
}

export interface CollaboratorRequestDetailDto {
  /** @nullable */
  companyName?: string | null;
  id?: string;
  /** @nullable */
  remarks?: string | null;
  requestId?: string;
}

export interface CollaboratorDto {
  /** @nullable */
  companyName?: string | null;
  id?: string;
  industry?: IndustryDto;
  /** @nullable */
  personInChargeFullName?: string | null;
  /** @nullable */
  picEmail?: string | null;
  /** @nullable */
  picPhoneNumber?: string | null;
}

export interface ChangePasswordDto {
  /** @nullable */
  confirmPassword?: string | null;
  /** @nullable */
  currentPassword?: string | null;
  /** @nullable */
  newPassword?: string | null;
}

export interface BuyRentRequestDetailDto {
  id?: string;
  interestType?: InterestType;
  isRent?: boolean;
  listing?: AdminListingDto;
  listingId?: string;
  requestId?: string;
}

export interface BusinessAffiliateSummaryDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  id?: string;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  profileImageUrl?: string | null;
  /** @nullable */
  username?: string | null;
}

export interface BusinessAffiliateDetailDto {
  address?: AddressDto;
  /** @nullable */
  appointments?: AppointmentDto[] | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  id?: string;
  /** @nullable */
  lastName?: string | null;
  operationalRegion?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  profileImageUrl?: string | null;
  user?: UserDto;
  userId?: string;
  /** @nullable */
  username?: string | null;
}

export interface BusinessAffiliateDetailDtoPagedResult {
  /** @nullable */
  items?: BusinessAffiliateDetailDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface BrowsingHistoryDto {
  id?: string;
  listing?: ListingDto;
  listingId?: string;
  userId?: string;
  viewedAt?: string;
}

export interface BrowsingHistoryDtoPagedResult {
  /** @nullable */
  items?: BrowsingHistoryDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface BrowsingHistoryDtoDataResponseDto {
  data?: BrowsingHistoryDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface AuthenticationResponseDto {
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  picFullName?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  refreshTokenExpiryDateTime?: string;
  /** @nullable */
  token?: string | null;
  tokenExpiration?: string;
  userId?: string;
}

export interface AuthenticationResponseDtoDataResponseDto {
  data?: AuthenticationResponseDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface AssignUserRoleCommand {
  /** @nullable */
  roleName?: string | null;
  userId?: string;
}

export type AppointmentType = typeof AppointmentType[keyof typeof AppointmentType];



export const AppointmentType = {
  Default: 'Default',
  ViewFullInspectionReport: 'ViewFullInspectionReport',
  SignBuyerAgreement: 'SignBuyerAgreement',
  MachineInspection: 'MachineInspection',
  SignSellerAgreement: 'SignSellerAgreement',
  SignRentingAgreement: 'SignRentingAgreement',
  SignRentingOutAgreement: 'SignRentingOutAgreement',
  MachineDelivery: 'MachineDelivery',
} as const;

export type AppointmentStatus = typeof AppointmentStatus[keyof typeof AppointmentStatus];



export const AppointmentStatus = {
  Default: 'Default',
  Scheduled: 'Scheduled',
  Completed: 'Completed',
  Cancelled: 'Cancelled',
} as const;

export interface AppointmentDto {
  address?: AddressDto;
  appointmentDateTime?: string;
  appointmentStatus?: AppointmentStatus;
  appointmentType?: AppointmentType;
  businessAffiliate?: BusinessAffiliateSummaryDto;
  createdAt?: string;
  id?: string;
  request?: RequestSummaryDto;
  updatedAt?: string;
  user?: UserDto;
}

export interface AppointmentDtoPagedResult {
  /** @nullable */
  items?: AppointmentDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface AppointmentDtoDataResponseDto {
  data?: AppointmentDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export type AdvertisementStatus = typeof AdvertisementStatus[keyof typeof AdvertisementStatus];



export const AdvertisementStatus = {
  Default: 'Default',
  Draft: 'Draft',
  Published: 'Published',
  Completed: 'Completed',
  Inactive: 'Inactive',
} as const;

export interface AdvertisementMediaDto {
  advertisementId?: string;
  id?: string;
  isThumbnail?: boolean;
  /** @nullable */
  mediaUrl?: string | null;
  /** @nullable */
  title?: string | null;
  type?: MediaType;
}

export interface AdvertisementMediaDtoPagedResult {
  /** @nullable */
  items?: AdvertisementMediaDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface AdvertisementMediaDtoDataResponseDto {
  data?: AdvertisementMediaDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface AdvertisementCategoryDto {
  id?: string;
  /** @nullable */
  name?: string | null;
}

export interface AdvertisementDto {
  advertisementCategory?: AdvertisementCategoryDto;
  /** @nullable */
  advertisementMedias?: AdvertisementMediaDto[] | null;
  advertisementStatus?: AdvertisementStatus;
  collaborator?: CollaboratorDto;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  endDate?: string | null;
  id?: string;
  isSystemAdvertisement?: boolean;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  urlToRedirectTo?: string | null;
}

export interface AdvertisementDtoPagedResult {
  /** @nullable */
  items?: AdvertisementDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface AdvertisementDtoDataResponseDto {
  data?: AdvertisementDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export interface AdvertisementCategoryDtoPagedResult {
  /** @nullable */
  items?: AdvertisementCategoryDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface AdvertisementCategoryDtoDataResponseDto {
  data?: AdvertisementCategoryDto;
  /** @nullable */
  errMessage?: string | null;
  isSuccess?: boolean;
}

export type AdministratorType = typeof AdministratorType[keyof typeof AdministratorType];



export const AdministratorType = {
  Default: 'Default',
  Operational: 'Operational',
  System: 'System',
} as const;

export interface AdministratorSummaryDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  id?: string;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  profileImageUrl?: string | null;
  /** @nullable */
  username?: string | null;
}

export interface AdministratorDetailDtoPagedResult {
  /** @nullable */
  items?: AdministratorDetailDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface AdminListingDto {
  /** @nullable */
  catalogUrl?: string | null;
  condition?: ListingCondition;
  createdAt?: string;
  distributorProfile?: DistributorSummaryDto;
  id?: string;
  isUserFavourite?: boolean;
  listingDetail?: ListingDetailDto;
  /** @nullable */
  listingMedias?: ListingMediaDto[] | null;
  listingStatus?: ListingStatus;
  listingType?: ListingType;
  location?: StatesAndTerritoriesOfMalaysia;
  machine?: MachineDto;
  /** @nullable */
  name?: string | null;
  price?: number;
  seller?: UserDto;
  /** @nullable */
  thumbnailUrl?: string | null;
  updatedAt?: string;
}

export interface AdminListingDtoPagedResult {
  /** @nullable */
  items?: AdminListingDto[] | null;
  itemsFrom?: number;
  itemsTo?: number;
  totalItemsCount?: number;
  totalPages?: number;
}

export interface AdminAdvertisementDto {
  advertisementCategory?: AdvertisementCategoryDto;
  /** @nullable */
  advertisementMedias?: AdvertisementMediaDto[] | null;
  advertisementStatus?: AdvertisementStatus;
  collaborator?: CollaboratorDto;
  createdAt?: string;
  createdBy?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  endDate?: string | null;
  id?: string;
  isSystemAdvertisement?: boolean;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  urlToRedirectTo?: string | null;
}

export interface AddressDto {
  /** @nullable */
  city?: string | null;
  id?: string;
  /** @nullable */
  name?: string | null;
  state?: StatesAndTerritoriesOfMalaysia;
  /** @nullable */
  street?: string | null;
  /** @nullable */
  street2?: string | null;
  user?: UserDto;
  /** @nullable */
  zipCode?: string | null;
}

export interface AdministratorDetailDto {
  address?: AddressDto;
  administratorType?: AdministratorType;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  id?: string;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  profileImageUrl?: string | null;
  reportTo?: AdministratorSummaryDto;
  /** @nullable */
  reportToId?: string | null;
  /** @nullable */
  subordinates?: AdministratorSummaryDto[] | null;
  user?: UserDto;
  userId?: string;
  /** @nullable */
  username?: string | null;
}

export interface AddUserFavouriteCommand {
  listingId?: string;
}

export interface AddBrowsingHistoryCommand {
  listingId?: string;
  /** @nullable */
  sessionId?: string | null;
}

